import Head from 'next/head'
import React from 'react'

const Login = () => {
  return (
    <>
    <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className='bg-pink-700'>login</div>
    </>
  )
}

export default Login